// auto-generated by build.js
var VER='ruc434-1785381375376';
self.addEventListener('install',function(e){self.skipWaiting()});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(ks){return Promise.all(ks.filter(function(k){return k!==VER}).map(function(k){return caches.delete(k)}))}).then(function(){return self.clients.claim()}))});
self.addEventListener('fetch',function(e){
  var url=new URL(e.request.url);
  if(e.request.method!=='GET')return;
  var isHTML=e.request.mode==='navigate'||url.pathname.endsWith('/index.html');
  if(isHTML){ /* network-first: 永不因缓存卡旧版 */
    e.respondWith(fetch(e.request).then(function(r){var c=r.clone();caches.open(VER).then(function(x){x.put(e.request,c)});return r;}).catch(function(){return caches.match(e.request)}));
    return;
  }
  if(/.(json|jpg|jpeg|png|webp|js|css)$/.test(url.pathname)||url.hostname==='cdn.jsdelivr.net'){ /* stale-while-revalidate */
    e.respondWith(caches.match(e.request).then(function(hit){
      var net=fetch(e.request).then(function(r){if(r.ok){var c=r.clone();caches.open(VER).then(function(x){x.put(e.request,c)});}return r;}).catch(function(){return hit;});
      return hit||net;
    }));
  }
});
